// Navegación común de la copia independiente.
const navigation = document.getElementById('navigation');
const links = [['Inicio','index.html'],['Servicios','servicios.html'],['Terapia individual','terapia-individual.html'],['Terapia familiar','terapia-familiar.html'],['Psicología energética','psicoenergetica.html'],['Trauma','trauma.html'],['EMDR','emdr.html'],['Recursos terapéuticos','recursos.html'],['Talleres','talleres.html'],['Sobre mí','sobre-mi.html'],['Blog','blog.html'],['Contacto','contacto.html']];
const base = document.querySelector('script[src$="script.js"]')?.src || new URL('script.js',document.baseURI).href;
const root = new URL('.',base);
if (navigation) navigation.replaceChildren(...links.map(([label,path])=>{const a=document.createElement('a');a.href=new URL(path,root).href;a.textContent=label;if(new URL(a.href).pathname===location.pathname)a.setAttribute('aria-current','page');return a;}));
const menu=document.querySelector('.menu');
if(menu&&navigation){menu.addEventListener('click',()=>{const expanded=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!expanded));navigation.classList.toggle('open',!expanded);});navigation.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{menu.setAttribute('aria-expanded','false');navigation.classList.remove('open');}));}
if(document.body.classList.contains('home')){
 const style=document.createElement('link');style.rel='stylesheet';style.href=new URL('home-fidelity.css',root).href;document.head.append(style);
 const adjustments=document.createElement('link');adjustments.rel='stylesheet';adjustments.href=new URL('home-fidelidad.css',root).href;document.head.append(adjustments);
 const footer=document.querySelector('footer');const contact=document.querySelector('#contacto');const quote=document.querySelector('.home-about blockquote');
 if(footer){const original=document.createElement('section');original.className='original-footer';original.setAttribute('aria-label','Contacto y pie de página');original.innerHTML='<p class="quote">«El mayor descubrimiento de mi generación es que un ser humano puede cambiar su vida cambiando su actitud mental»<br><strong>William James</strong>, considerado uno de los padres de la Psicología</p><span class="contact-label">CONTACTO</span><a class="info-link" href="./contacto.html">INFO</a><p>Félix Larriba Catalán · Psicólogo y psicoterapeuta · Tenerife<br>Atención online · Presencial previa valoración</p><a class="author-link" href="https://www.felixlarriba.com/">▣ Visita mi web de autor</a><p class="welcome">Bienvenid@</p><p><a href="mailto:Psicologiaenergetica.net@gmail.com">Psicologiaenergetica.net@gmail.com</a><br><a href="tel:+34629468154">+34 629468154 Watsup</a></p><p class="disclaimer">El contenido de estas páginas, como de toda información obtenida en internet, tiene que ser interpretado y contrastado por profesionales acreditados, el autor queda exento de toda responsabilidad de la utilización que se haga de ellas, sin la guía profesional adecuada.</p><p class="copyright">©2026 por Psicoterapia Integral</p>';footer.replaceWith(original);}
 if(contact)contact.hidden=true;if(quote)quote.hidden=true;
 const cta=document.querySelector('.hero .button');if(cta){cta.textContent='Da el primer paso hoy →';cta.href=new URL('contacto.html',root).href;}
 // En la captura original, el cuadro de ayuda aparece inmediatamente después del encabezado y antes de las tarjetas.
 const hero=document.querySelector('.hero');const help=document.querySelector('.home-help');
 if(hero&&help){hero.after(help);help.innerHTML='<h2>¿En qué puedo ayudarte?</h2><ul class="home-help-grid"><li>🌱 Ansiedad y estrés</li><li>🌟 Depresión y tristeza profunda</li><li>🔒 Bloqueos emocionales</li><li>💔 Conflictos familiares y patrones repetitivos</li><li>🌀 Procesamiento de traumas y experiencias difíciles</li><li>🎯 Búsqueda de propósito y sentido de vida</li></ul>';}
 // Las ocho tarjetas reproducen los títulos y el orden visible en la captura del sitio original.
 if(help){const cards=[['Formación y experiencia','sobre-mi.html','https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=250&q=75'],['Resiliencia','emdr.html','https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=250&q=75'],['Cómo sanar con la T. de Regresión','trauma.html','https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?auto=format&fit=crop&w=250&q=75'],['Desarrollo Personal y Mindfulness','servicios.html','https://images.unsplash.com/photo-1472214103451-9374bd1c798e?auto=format&fit=crop&w=250&q=75'],['Implicaciones clínicas','terapia-individual.html','https://images.unsplash.com/photo-1499209974431-9dddcece7f88?auto=format&fit=crop&w=250&q=75'],['Preguntas sobre la Terapia. Faqs','recursos.html','https://images.unsplash.com/photo-1456324504439-367cee3b3c32?auto=format&fit=crop&w=250&q=75'],['Psicología Energética','psicoenergetica.html','https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=250&q=75'],['Vídeos y Divulgación','blog.html','https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?auto=format&fit=crop&w=250&q=75']];const grid=document.createElement('div');grid.className='home-visual-nav';grid.setAttribute('aria-label','Accesos a contenidos');cards.forEach(([label,path,img])=>{const a=document.createElement('a');a.href=new URL(path,root).href;const image=document.createElement('img');image.src=img;image.alt='';image.loading='lazy';const text=document.createElement('span');text.textContent=label;a.append(image,text);grid.append(a);});help.after(grid);}
}
